### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by armanrahman22** [fixpoint/azblob-download-artifact#11]
Why is there a slash here? It causes there to never be a match.
https://github.com/fixpoint/azblob-download-artifact/blob/e41ced1257eb342230f3add4af1ba70ae7b51f16/src/download.ts#L22

I would suggest something like this which is more readable:

```javascript
for await (const blob of containerClient.listBlobsFlat()) {
    if (blob.name === name) {
      const dst = join(path || name, relative(name, blob.name));
      core.info(`Downloading ${blob.name} to ${dst} ...`);
      await fs.mkdir(dirname(dst), { recursive: true });
      const blockClient = await containerClient.getBlockBlobClient(blob.name);
      await blockClient.downloadToFile(dst);
      return;
    }
}
```

**Comment by lambdalisue** [comment]
Because it downloads all entities **under** the `name`. This action is assumed to be used with https://github.com/fixpoint/azblob-upload-artifact thus it is not for downloading a single file.
